/** Design tokens transcribed from DESIGN.md frontmatter (colors/rounded/spacing). */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#43474f",
        "inverse-surface": "#2d3133",
        outline: "#737780",
        "outline-variant": "#c3c6d1",
        primary: "#001e40",
        "on-primary": "#ffffff",
        "primary-container": "#003366",
        "on-primary-container": "#799dd6",
        secondary: "#505f76",
        "on-secondary": "#ffffff",
        "secondary-container": "#d0e1fb",
        "on-secondary-container": "#54647a",
        tertiary: "#00231f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#003a35",
        "on-tertiary-container": "#38ac9f",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#a7c8ff",
        "on-primary-fixed": "#001b3c",
        "on-primary-fixed-variant": "#1f477b",
        "secondary-fixed": "#d3e4fe",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed": "#89f5e7",
        "tertiary-fixed-dim": "#6bd8cb",
        "on-tertiary-fixed": "#00201d",
        "on-tertiary-fixed-variant": "#005049",
        "focus-ring": "#2563eb",
        background: "#f7f9fb",
        "surface-variant": "#e0e3e5",
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
